# Generated by Django 4.2 on 2023-04-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
    ]
